shutdown_costmaps: false

controller_frequency: 4.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 3.0

oscillation_timeout: 15.0
oscillation_distance: 0.2

max_planning_retries: 3

recovery_behavior_enabled: true
clearing_rotation_allowed: true

recovery_behaviors:
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'clearing_rotation'
    type: 'rotate_recovery/RotateRecovery'
    
conservative_reset:
  reset_distance: 3.0
  layer_names: [obstacle_layer]

aggressive_reset:
  reset_distance: 0.3
  layer_names: [obstacle_layer]


# Other References
# ================
# url: http://wiki.ros.org/move_base
# url: http://wiki.ros.org/move_slow_and_clear
# url: https://blog.csdn.net/qq_41906592/article/details/89185808